### ISSUE TITLE
Recyclerview Support

### ISSUE THREAD

**Issue by svkdvlp** [nukc/StateView#10]
can it be injected with recyclerview?

I got 

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$ViewHolder.shouldIgnore()

**Comment by nukc** [comment]
supported in v1.3.3, [sample #InjectRvActivity.java](https://github.com/nukc/StateView/blob/master/app/src/main/java/com/github/nukc/sample/InjectRvActivity.java) .
