### ISSUE TITLE
BUG 多次切换不显示

### ISSUE THREAD

**Issue by 957919019** [nukc/StateView#11]
我将网络关闭，多次调用showLoading和showRetry后，showRetry()执行后retry不显示了，打断点基本会在第三次第四次发生，不打断点，第二次就会发生，

**Comment by 957919019** [comment]
这个问题在我注释掉
//        mStateView.setAnimatorProvider(new FlipAnimatorProvider());
这行代码以后得以解决，so ，please fix it

**Comment by 957919019** [comment]
另外还有一些问题就是，在showContent以后，页面的DrawerLayout的滑动以及控件的点击事件都已经被消费，

**Comment by nukc** [comment]
了解了，之后我会进行排查

**Comment by nukc** [comment]
@957919019 试下 v1.3.4，对于 DrawerLayout 的问题，你可以看看 [DrawerLayoutActivity](https://github.com/nukc/StateView/blob/master/app/src/main/java/com/github/nukc/sample/DrawerLayoutActivity.java)，这样是否可以解决你的问题。另外一些比较特殊或比较复杂的布局，StateView 放在 layout(.xml) 里使用会更灵活。
