### ISSUE TITLE
您好，关于showLoading的疑问

### ISSUE THREAD

**Issue by po1arbear** [nukc/StateView#12]
请问showLoading的时候点击Loading图以外的地方Loading状态的取消是否可控

**Comment by nukc** [comment]
在点击事件里可自行控制：
显示空视图: mStateView.showEmpty();
显示加载视图: mStateView.showLoading();
显示重试视图: mStateView.showRetry();
显示内容: mStateView.showContent();

**Comment by po1arbear** [comment]
您好，我在页面未加载完时调用showLoading，加载完毕后才调用showContent，现在遇到的问题是页面未加载完时无法操作界面，该如何处理呢？有没有类似于dialog的cancelable属性

**Comment by nukc** [comment]
你是要整个页面都显示 loading ，还是只有页面的一部分显示 loading?
下图是只对页面一部分进行操作，上部分是一个 ViewGroup, 下部分是按钮之类的部分:
<img width="375" alt="qq20180123-143552 2x" src="https://user-images.githubusercontent.com/9924409/35261356-be17512c-004a-11e8-8dc9-fbf8bc676a01.png">
使用代码的话，可以 inject 到上部分的 R.id.content 中，或者在 xml (layout) 里直接写入。
或许你可以参考一下 demo 中的 [AnimatorActivity](https://github.com/nukc/StateView/blob/master/app/src/main/java/com/github/nukc/sample/AnimatorActivity.java)。
对于你说的有没有类似于 dialog 的 cancelable 属性，道理其实是一样的，dialog 区域外点击可取消；所以使用 StateView 不要直接 inject 到 Activity 或 Fragment 中，而是 inject 到 layout 中的其中一个区域，然后在这个区域外的地方自己做点击事件进行操控 StateView 就可以了。
