### ISSUE TITLE
ConstraintLayout适配问题

### ISSUE THREAD

**Issue by THEONE10211024** [nukc/StateView#13]
在ConstraintLayout中StateView会有问题

**Comment by nukc** [comment]
是只要在 ConstraintLayout 中就会有问题吗？还是在某些条件下才会，会出现什么样的问题，能否描述一下

**Comment by THEONE10211024** [comment]
只要在ConstraintLayout中就会有问题，通过getLayoutParam获取的宽高都不对

**Comment by nukc** [comment]
了解了，我之前有试过，但没发现问题，之后我再多试试一些复杂的情况看看

**Comment by THEONE10211024** [comment]
版本是：1.1.2
布局文件里这样写的：
`
<StateView
android:visibility="gone"
       android:id="@+id/state_view"
       android:layout_width="0dp"
       android:layout_height="0dp"
       layout="@layout/bosshd_common_reload_layout"
       app:layout_constraintStart_toStartOf="@id/dish_rv"
       app:layout_constraintEnd_toEndOf="@id/dish_rv"
       app:layout_constraintTop_toTopOf="@id/dish_rv"
       app:layout_constraintBottom_toBottomOf="@id/dish_rv">
</StateView>`
然后在方法里
`private View inflate(@LayoutRes int layoutResource, @ViewType int viewType) {
        final ViewParent viewParent = getParent();

        if (viewParent != null && viewParent instanceof ViewGroup) {
            if (layoutResource != 0) {
                final ViewGroup parent = (ViewGroup) viewParent;
                final LayoutInflater factory;
                if (mInflater != null) {
                    factory = mInflater;
                } else {
                    factory = LayoutInflater.from(getContext());
                }
                final View view = factory.inflate(layoutResource, parent, false);

                final int index = parent.indexOfChild(this);
                // 防止还能触摸底下的 View
                view.setClickable(true);
                // 先不显示
                view.setVisibility(GONE);

                final ViewGroup.LayoutParams layoutParams = getLayoutParams();
                if (layoutParams != null) {
                    if (parent instanceof RelativeLayout) {
                        ViewGroup.MarginLayoutParams lp = (ViewGroup.MarginLayoutParams) layoutParams;
                        mLayoutParams.setMargins(lp.leftMargin, lp.topMargin,
                                lp.rightMargin, lp.bottomMargin);

                        parent.addView(view, index, mLayoutParams);
                    } else {
                        parent.addView(view, index, layoutParams);
                    }
                } else {
                    parent.addView(view, index);
                }

                if (mLoadingView != null && mRetryView != null && mEmptyView != null) {
                    parent.removeViewInLayout(this);
                }

                if (mInflateListener != null) {
                    mInflateListener.onInflate(viewType, view);
                }

                return view;
            } else {
                throw new IllegalArgumentException("StateView must have a valid layoutResource");
            }
        } else {
            throw new IllegalStateException("StateView must have a non-null ViewGroup viewParent");
        }
    }`
返回的View 宽和高都为0

**Comment by nukc** [comment]
在这里获取 view 的 width 和 height 是 0 的，测量在这方法之后。确实在 xml 直接使用这样使用是无法正常显示，在这里会调用 ```parent.addView(view, index, layoutParams);``` layoutParams 是 xml 里 StateView 的设置，对于在 ConstraintLayout 并没有做更多的兼容，如果是填充 ConstraintLayout 还好，设置 match_parent 貌似可以解决，看到你是根据 @id/dish_rv 设置位置的，我这边测试是 loadingView(等) 是可以显示，但里面的子 View 无法显示，

**Comment by nukc** [comment]
试试 1.5.1 版本是否已经修复
```gradle 
implementation 'com.github.nukc.stateview:library:1.5.1'
```
