### ISSUE TITLE
有个小小的建议，就是数据为空的情况下是否可以增加一个点击重试！ 有些情况需要再次刷新当前页面。

### ISSUE THREAD

**Issue by FanChael** [nukc/StateView#21]
我目前是导入module自己做了空数据重试回调。

**Comment by FanChael** [comment]
![TIM截图20190718135103](https://user-images.githubusercontent.com/968456/61432483-322a4c00-a963-11e9-8832-103b410e5d6d.png)
大佬，类似这样是不是也可以增加一个回调设置....

**Comment by nukc** [comment]
其实可以这样，当 showEmpty() 会返回 emptyView，可以对其做 click 的监听，等以后有时间，可能会进行 kotlin 重构和增强

**Comment by FanChael** [comment]
OK
