### ISSUE TITLE
一定要引入 constraint-layout:1.1.2

### ISSUE THREAD

**Issue by ivalimmb** [nukc/StateView#22]
如题  需要implementation 'com.android.support.constraint:constraint-layout:1.1.2'   不然直接会崩溃

**Comment by nukc** [comment]
在某个版本对 ConstraintLayout 做了兼容，所以是需要的

**Comment by nukc** [comment]
可以查看：
[compileOnly 'com.android.support.constraint:constraint-layout:1.1.3'](https://github.com/nukc/StateView/blob/master/library/build.gradle#L28)
[Injector.java](https://github.com/nukc/StateView/blob/master/library/src/main/java/com/github/nukc/stateview/Injector.java)
