### ISSUE TITLE
关于leak的问题

### ISSUE THREAD

**Issue by FanChael** [nukc/StateView#24]
小锅锅，这个如果在转圈，然后立即退出当前页面，用leakcanary检测发现一个Stateview关于activity is destroyed的信息。崩溃倒是不崩溃。  但是感觉内存有泄漏。比如说是否需要退出界面，是否Stateview相关的资源，动画这些？

**Comment by nukc** [comment]
切换动画只在切换视图的时候执行，核心方法跟 ViewStub 是一样的，你可以看看你是否在其它地方引用了 view ，对于此类情况，如果需要，可尝试用弱引用

**Comment by FanChael** [comment]
嗯。我再研究下。我是rx请求里面showDialog（这个就是调用的StateView）；我onDestroy释放了请求的，但是估计Stateview还持有。
