### ISSUE TITLE
兼容适配

### ISSUE THREAD

**Issue by Payaml** [nukc/StateView#25]
与 CoordinatorLayout + AppBarLayout + CollapsingToolbarLayout 一起使用时, 网络请求完成后都是没问题的, 但是当锁屏或让当前页面置于后台再返回, 页面100%会卡住, 无法操作, 怀疑页面上还有一层遮罩层, 所以才导致的被 StateView 覆盖的地方都无法操作

**Comment by nukc** [comment]
用 Layout Inspector 看看视图情况，StateView 自身是不绘制的且不显示的，show 操作是 ViewStub 同理，至于顶层是否有什么遮罩层，可以进一步分析

**Comment by Payaml** [comment]
当我不使用这样的组合的情况下一切都是正常的, StateView消失掉了, 页面显示出来了, 所以我觉得应该是哪里的兼容性问题

**Comment by Payaml** [comment]
当我不使用这样的组合的情况下一切都是正常的, 所以我觉得应该是哪里的兼容性问题

**Comment by nukc** [comment]
这是 Demo ，https://github.com/nukc/StateView/blob/kotlin/app/src/main/java/com/github/nukc/sample/CoordinatorLayoutActivity.kt
