### ISSUE TITLE
StateView的inflate方法一些困惑

### ISSUE THREAD

**Issue by brandlee** [nukc/StateView#26]
麻烦请教一下，在StateView的inflate方法里面，最后这一行代码：
`                if (loadingView != null && retryView != null && emptyView != null) {
                    viewParent.removeViewInLayout(this)
                }`
具体作用是什么呢？

**Comment by brandlee** [comment]
还有一个就是在wrap方法里面：
        fun wrap(view: View): StateView {
            val parent = view.parent
            if (parent is ViewGroup) {
                if (parent is ConstraintLayout) {
                    return Injector.matchViewIfParentIsConstraintLayout(parent, view)
                }
                if (parent is RelativeLayout) {
                    return Injector.matchViewIfParentIsRelativeLayout(parent, view)
                }

                // will increase the layout level
                parent.removeView(view)
                val wrap = FrameLayout(view.context)
                parent.addView(wrap, view.layoutParams)
                wrap.addView(view, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
                val stateView = StateView(view.context)
                wrap.addView(stateView, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
                Injector.setStateListAnimator(stateView, view)
                return stateView
            }`
添加wrap的时候，是不是需要考虑到子View的index？
`

**Comment by nukc** [comment]
removeViewInLayout 就是把 StateView 自己给移除了，在对状态图都完成使命后，自身的属性便用不上了，也就没必要留着了。
目前只是考虑到添加目标 view 的后面，并没有考虑其它子 view，默认 index 是 -1，那自然会 add 都最后了。
inject(index, view)
wrap(index, view)
也是在我重写后有在考虑的事情

**Comment by brandlee** [comment]
对于inject和wrap这块还是有一些困惑，能帮忙讲解一下这块代码的思路么？
`@JvmStatic
        fun inject(view: View): StateView {
            return when (view) {
                is ViewGroup -> inject(view)
                else -> wrap(view)
            }
        }

        @JvmStatic
        fun inject(viewGroup: ViewGroup): StateView {
            if (viewGroup is LinearLayout || viewGroup is ScrollView || viewGroup is AdapterView<*> ||
                (viewGroup is ScrollingView && viewGroup is NestedScrollingChild) ||
                (viewGroup is NestedScrollingParent && viewGroup is NestedScrollingChild)
            ) {
                return if (viewGroup.parent is ViewGroup) {
                    wrap(viewGroup)
                } else {
                    Injector.wrapChild(viewGroup)
                }
            }

            // match the viewGroup
            val stateView = StateView(viewGroup.context)
            viewGroup.addView(stateView, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
            return stateView
        }`

**Comment by nukc** [comment]
如果目标 view 是 ViewGroup，那就是有可能直接把 StateView 添加到 ViewGroup 里面（直接 match 长宽，show 状态图的时候就可以遮住目标 view(ViewGroup) 了）；否则就只能添加到目标 view 的父布局里。

```java
    @JvmStatic
    fun inject(viewGroup: ViewGroup): StateView {
        // 需要判断类型，都是一些布局特性，比如 LinearLayout , 直接 addView 的话是无法达到目的的
        if (viewGroup is LinearLayout || viewGroup is ScrollView || viewGroup is AdapterView<*> ||
            (viewGroup is ScrollingView && viewGroup is NestedScrollingChild) ||
            (viewGroup is NestedScrollingParent && viewGroup is NestedScrollingChild)
        ) {
            return if (viewGroup.parent is ViewGroup) {
                wrap(viewGroup)
            } else {
                Injector.wrapChild(viewGroup)
            }
        }

        // match the viewGroup
        val stateView = StateView(viewGroup.context)
        viewGroup.addView(stateView, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
        return stateView
    }
```
