### ISSUE TITLE
Kotlin版本对于包裹ScrollView的子ViewGroup有问题

### ISSUE THREAD

**Issue by brandlee** [nukc/StateView#27]
`<android.support.v4.widget.NestedScrollView
        android:id="@+id/nested_scrollview"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:id="@+id/ll_content"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <include
                layout="@layout/one" />

            <include
                layout="@layout/two" />
        </LinearLayout>
    </android.support.v4.widget.NestedScrollView>`

如果我对ll_content进行inject的时候，是有问题的，layout two会不展示出来

**Comment by brandlee** [comment]
主要是这一段代码：
`               // will increase the layout level
                parent.removeView(view)
                val wrap = FrameLayout(view.context)
                parent.addView(wrap, view.layoutParams)
                wrap.addView(view, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
                val stateView = StateView(view.context)
                wrap.addView(stateView, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
                Injector.setStateListAnimator(stateView, view)`

**Comment by nukc** [comment]
``@layout/one`` 可以显示， ``two``不可以？

**Comment by brandlee** [comment]
对的

**Comment by nukc** [comment]
可以看下新加的 demo

**Comment by brandlee** [comment]
这个问题是解决了么？

**Comment by nukc** [comment]
并未发现这个问题
