### ISSUE TITLE
setEmptyView这个api未能生效

### ISSUE THREAD

**Issue by GoombaCN** [nukc/StateView#30]
代码如下
 
stateView = StateView.inject(activity);
View view = LayoutInflater.from(this).inflate(R.layout.view_empty, null);
stateView.setEmptyView(view);
stateView.showEmpty();

这样不会如预期一样显示空布局
但是换成：

stateView = StateView.inject(activity);
stateView.setEmptyResource(R.layout.view_empty);
stateView.showEmpty();

就可以正常显示空布局 
请教一下 我应该如何解决呢 @nukc

**Comment by nukc** [comment]
并无 ``setEmptyView`` 方法。如果是想拿到 ``emptyView``
``showEmpty()`` 返回的 view 就是。

**Comment by nukc** [comment]
你依赖的应该是 kotlin 版本的，刚刚看了下，没加 private set 了。。直接之后我看看是公开还是私有，再测一边

**Comment by nukc** [comment]
直接 setEmptyView 无效的原因是， 这个要设置的 view 并没有 add 的 parent 里面，所以不在视图结构里，怎样操作都不会显示的。
直接 setEmptyView 并没有通过这个方法 [inflate](https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L207)

**Comment by GoombaCN** [comment]
> 
> 
> 直接 setEmptyView 无效的原因是， 这个要设置的 view 并没有 add 的 parent 里面，所以不在视图结构里，怎样操作都不会显示的。
> 直接 setEmptyView 并没有通过这个方法 [inflate](https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L207)

那请教一下您 如果我想传一个自定义的emptyView 应该如何设置呢
比方说MainActivity和Main2Activity都需要使用一种上图下文样式的布局 但他们的图片和文字不同 
这时候我去写两个xml 里面样式一样 然后各自设置不同的图片资源和文字资源 
然后在MainActivity调用setEmptyResource(R.layout.view_empty);
在Main2Activity调用setEmptyResource(R.layout.view_empty2);
如果有20个页面 我需要创建20个xml

这样似乎不是正确的做法吧 您方便指点一下吗 @nukc

**Comment by nukc** [comment]
不出意外，今天应该可以出个版本

**Comment by nukc** [comment]
[Demo](https://github.com/nukc/StateView/blob/kotlin/app/src/main/java/com/github/nukc/sample/SetViewActivity.java#L34)

**Comment by GoombaCN** [comment]
> 
> 
> [Demo](https://github.com/nukc/StateView/blob/kotlin/app/src/main/java/com/github/nukc/sample/SetViewActivity.java#L34)

试了一下2.1正常了 由衷感谢大佬的帮助！
