### ISSUE TITLE
setRetry相关的api异常

### ISSUE THREAD

**Issue by GoombaCN** [nukc/StateView#31]
版本 implementation 'com.github.nukc.stateview:kotlin:2.1'
代码如下：

        View view = LayoutInflater.from(this).inflate(R.layout.view_nodata, null);
     
        stateView.setOnRetryClickListener(new StateView.OnRetryClickListener() {
            @Override
            public void onRetryClick() {
                Toast.makeText(MainActivity.this, "重试", 0).show();
                stateView.showContent();
            }
        });
        stateView.showRetry();

此时有两个问题：
1.onRetryClick方法未生效 但可以通过给view自行setOnClickListener规避 代码如下：

 retryView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(MainActivity.this, "重试", 0).show();
                stateView.showContent();
            }
        });

2.但是在retryView的点击事件中  stateView.showContent();未能生效 依然显示retryView 但是吐司正常显示 此问题影响较大 

3.使用setRetryResource 未能正常显示对应的view 代码如下
stateView.setRetryResource(R.layout.view_nodata);
stateView.setRetryView(view);

还望大佬指点一二  提前谢过 @nukc @luobinwei

**Comment by nukc** [comment]
``` setRetryResource ``` 只是预设值（此时并没有添加到视图结构中），当 showRetry() 调用时 retryView == null 的时候会通过 inflate 方法加入。
``` setRetryView ``` 会立即把传入的 view 加入

**Comment by nukc** [comment]
setXXXView 方法逻辑需要修改了，改成设置的时候不马上加入视图，当调用 showXX() 的时候才将其加入并显示

**Comment by GoombaCN** [comment]
> 
> 
> `setRetryResource` 只是预设值（此时并没有添加到视图结构中），当 showRetry() 调用时 retryView == null 的时候会通过 inflate 方法加入。
> `setRetryView` 会立即把传入的 view 加入

这里我粘错代码了 我重新粘一下

stateView = StateView.inject(this);
stateView.setRetryResource(R.layout.view_nodata);
 stateView.setOnRetryClickListener(new StateView.OnRetryClickListener() {
            @Override
            public void onRetryClick() {
                Toast.makeText(MainActivity.this, "重试", 0).show();
                stateView.showContent();
            }
        });
stateView.showRetry();


view_nodata.xml代码如下 

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/no_data"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:text="没有数据"
        android:textSize="20dp" />
</RelativeLayout>

按理说应该显示出来这个布局的内容 但实际上并不行 页面是空白的 
而且OnRetryClickListener里面的代码 可以生效一次 之后再点击就没有效果了

**Comment by GoombaCN** [comment]
> 
> 
> setXXXView 方法逻辑需要修改了，改成设置的时候不马上加入视图，当调用 showXX() 的时候才将其加入并显示

setRetry相关代码不生效 是您说的这个原因导致吗

**Comment by nukc** [comment]
view_nodata.xml 就只有一个 TextView 吗，设置个大小或 match_parent
```xml
<TextView
    android:id="@+id/no_data"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_centerInParent="true"
    android:text="没有数据"
    android:textSize="20dp" />
```

**Comment by nukc** [comment]
> setRetry相关代码不生效 是您说的这个原因导致吗

不是，这块是需要优化的

**Comment by GoombaCN** [comment]
> 
> 
> > setRetry相关代码不生效 是您说的这个原因导致吗
> 
> 不是，这块是需要优化的

在retryView的点击事件中 stateView.showContent();未能生效 依然显示retryView
那这个问题 是我这边代码没有正确调用引起的吗
还是说 需要您更新版本才能解决此问题

**Comment by GoombaCN** [comment]
> 
> 
> view_nodata.xml 就只有一个 TextView 吗，设置个大小或 match_parent
> 
> ```
> <TextView
>     android:id="@+id/no_data"
>     android:layout_width="wrap_content"
>     android:layout_height="wrap_content"
>     android:layout_centerInParent="true"
>     android:text="没有数据"
>     android:textSize="20dp" />
> ```

对 因为是在demo中尝试复现此问题 就只写了一个TextView
设置宽度match_parent后依然不显示
设置宽度为80dp后也不显示

**Comment by GoombaCN** [comment]
> 
> 
> view_nodata.xml 就只有一个 TextView 吗，设置个大小或 match_parent
> 
> ```
> <TextView
>     android:id="@+id/no_data"
>     android:layout_width="wrap_content"
>     android:layout_height="wrap_content"
>     android:layout_centerInParent="true"
>     android:text="没有数据"
>     android:textSize="20dp" />
> ```


这样无法显示：
stateView = StateView.inject(this);
stateView.setRetryResource(R.layout.view_nodata);
stateView.showRetry();

这样正常显示：
stateView = StateView.inject(this);
View view = LayoutInflater.from(this).inflate(R.layout.view_nodata, null);
 stateView.setRetryView(view);
 stateView.showRetry();

**Comment by nukc** [comment]
设置下颜色看看：
```xml
android:textColor="@android:color/black" 
```

**Comment by GoombaCN** [comment]
> 
> 
> 设置下颜色看看：
> 
> ```
> android:textColor="@android:color/black" 
> ```

我试了一下 #333333这个色值 也就是黑灰色 是可以显示的
但是用白色#ffffff这个色值就不行 是显示不出来的
这是什么原理呢

**Comment by nukc** [comment]
你可以试下在 TextView 外面加个父类，然后不设置颜色

**Comment by GoombaCN** [comment]
> 
> 
> 你可以试下在 TextView 外面加个父类，然后不设置颜色


我尝试了一下 代码如下

![图片](https://user-images.githubusercontent.com/15976623/90877915-6af2eb00-e3d7-11ea-88b0-4027c47a629d.png)


最外层的RelativeLayout 无论是不设置background 还是设置白色(#ffffff) 都无法正常显示
但使用#333333可以正常显示

</RelativeLayout>

**Comment by nukc** [comment]
初步判断是主题颜色问题，因为 setRetryResource ， showRetry() 方法，主要就是 inflate 到 view，然后调用 parent 的 addView

**Comment by nukc** [comment]
![image](https://user-images.githubusercontent.com/9924409/90878673-624ee480-e3d8-11ea-816b-b15ef719f85d.png)
使用 Layout Inspector 看看就知道， view 是已经 add 到 parent，大小 ，visibility 都是正常的，字体颜色可能是跟背景一样导致看不到
