### ISSUE TITLE
StateView.inject(rv)没有效果，布局如下：

### ISSUE THREAD

**Issue by SuperAton** [nukc/StateView#32]
<com.scwang.smart.refresh.layout.SmartRefreshLayout
        android:id="@+id/refreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:srlEnablePreviewInEditMode="false"
        app:srlEnableAutoLoadMore="false"
        app:srlDisableContentWhenLoading="true"
        app:srlDisableContentWhenRefresh="true">
        <com.scwang.smart.refresh.header.ClassicsHeader
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:srlFinishDuration="0"
            app:srlDrawableArrowSize="40dp"
            app:srlTextSizeTitle="14sp"
            app:srlTextSizeTime="12sp"
            app:srlDrawableArrow="@mipmap/refresh_arrow"/>
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
        <com.scwang.smart.refresh.footer.ClassicsFooter
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:srlFinishDuration="0"
            app:srlDrawableArrowSize="40dp"
            app:srlTextSizeTitle="14sp"
            app:srlTextSizeTime="12sp"
            app:srlDrawableArrow="@mipmap/refresh_arrow"/>
    </com.scwang.smart.refresh.layout.SmartRefreshLayout>

**Comment by SuperAton** [comment]
<img width="992" alt="QQ20200825-093641@2x" src="https://user-images.githubusercontent.com/25004643/91112758-86e7dc80-e6b6-11ea-8689-56e8979f039c.png">
StateView.inject(rv)后rv高度为0了

**Comment by nukc** [comment]
FrameLayout 的宽高是多少?
rv add 的代码是在这里，都是 MATCH_PARENT。 [StateView.kt#L388](https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L388)

对于一些不确定的第三方控件，或者比较复杂的需求，都可以在 xml 里直接使用

**Comment by SuperAton** [comment]
FrameLayout的宽高都是0，FrameLayout好像是代码里面加进去的，原来的布局没有FrameLayout
![image](https://user-images.githubusercontent.com/25004643/91120414-30839980-e6c8-11ea-8040-e0f72b175ed0.png)

**Comment by nukc** [comment]
就是代码创建的，以代替自己在 xml 里布置

**Comment by nukc** [comment]
还要看 inject 的 view 是什么类型，rv 是走 wrap 的，还要看 rv 的 parent 是谁，看你的是第三方的一个下拉刷新控件吧，所以这个还要看父类的测量定位，就像对于 ConstraintLayout 和 RelativeLayout 一样。 无疑 xml 自己布置是最灵活的
