### ISSUE TITLE
可否建一个群？

### ISSUE THREAD

**Issue by OnClickListener2048** [nukc/StateView#33]

**Comment by nukc** [comment]
有问题可直接在这提问

**Comment by OnClickListener2048** [comment]
我inject了一个布局中的View  这个View的宽高都是包裹内容  但是StateView最后显示的却是matchparent了  也就是变成该View的父布局相同的大小了

**Comment by OnClickListener2048** [comment]
我希望StateView也应该是包裹内容的 只包裹该View

**Comment by nukc** [comment]
看一下这里的静态方法就知道逻辑是怎样的，https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L348
