### ISSUE TITLE
StateView遮住原来布局

### ISSUE THREAD

**Issue by tbg1234567890** [nukc/StateView#37]
如果原来的父布局是FramLayout，有多个子布局做切换，当给第一个子布局注入StateView后，第一个子布局将变成最顶层的子布局（因为有remove和add操作），这样就会打乱了原来的布局层次，希望替换后还在原来的索引位

**Comment by tbg1234567890** [comment]
if (viewParent instanceof ViewGroup) {
                    ViewGroup rootGroup = (ViewGroup) viewParent;
                    // 获取原来位置index
                    final int indexOfChild = rootGroup.indexOfChild(parent);
                    // 把 parent 从它自己的父容器中移除
                    rootGroup.removeView(parent);
                    // 然后替换成新的
                    rootGroup.addView(root, indexOfChild);

                    Injector.changeChildrenConstraints(rootGroup, root, parent.getId());
                }

**Comment by nukc** [comment]
给父布局注入不行吗

**Comment by LeeUsun** [comment]
同样遇到这个问题了，打乱原来的布局层次结构

**Comment by nukc** [comment]
StateView 版本，用的哪个方法，目标控件是什么。如果直接在 layout.xml 布局文件中使用，是最大兼容的
