### ISSUE TITLE
OnInflateListener 只会初始化调用一次，导致的问题

### ISSUE THREAD

**Issue by LLQQHH** [nukc/StateView#38]
显示错误的界面，一般是显示服务器返回的文字，显示在错误界面！但是因为你这边只有第一次我能拿到那个错误界面的View！导致我第二次要改变文字无法实现，因为第二次现在拿不到View了。现在解决办法是，只能在第一次调用OnInflateListener 的时候，把显示错误的TextView搞成activity的成员变量！然后调用showError之前，去设置文本！但是这样有点不够优雅！

**Comment by nukc** [comment]
这样确实是不优雅的，但是 showError()/showRetry() 会返回 View , 可直接对该 View 进行操作

**Comment by LLQQHH** [comment]
好的，我试试库很好用，但是有一些问题跟你讨论下
1.这边有能扩展showCustomXXX()的功能吗，因为有时候不止你库里面定义的那几种状态页面！自己想增加某种状态页
2.mStateView.setOnRetryClickListener(new StateView.OnRetryClickListener() {
        @Override
        public void onRetryClick() {
            //do something, no need to call showLoading()
            //不需要调用showLoading()方法, StateView自会调用
        }
    })
这个点击重试一般是点击重试页面的某个按钮，而不是整个页面！

**Comment by nukc** [comment]
目前可以这样
```kotlin
stateView.showRetry().findViewById<Button>(R.id.btn_xx).setOnClickListener {
    // do
}
```
拓展的话，现在还没有想法

**Comment by LLQQHH** [comment]
好的，了解！

**Comment by nukc** [comment]
@LLQQHH 已经重构了，现在 v3 版本支持任意个 Custom

https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L103

https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L120
