### ISSUE TITLE
关于setOnInflateListener()方法

### ISSUE THREAD

**Issue by Awoodwhale** [nukc/StateView#41]
从README中看到了setOnInflateListener()这个方法，但是今天在使用的时候发现，在kotlin重构之后，onInflate()方法并没有实现？并且 StateView.EMPTY类似的常量我也找不到了。

版本是最新的3.0.1

```java
    mStateView.setOnInflateListener(new StateView.OnInflateListener() {
        @Override
        public void onInflate(@StateView.ViewType int viewType, View view) {
            if (viewType == StateView.EMPTY) {
                // set text or other
                ViewGroup emptyView = (ViewGroup) view;
                TextView tvMessage = (TextView) emptyView.findViewById(R.id.tv_message);
                ImageView ivState = (ImageView) emptyView.findViewById(R.id.iv_state);
                tvMessage.setText("custom message");
                ivState.setImageResource(R.drawable.retry);
            } else if (viewType == StateView.RETRY) {
                // ...
            }
        }
    });
```

**Comment by nukc** [comment]
OnInflateListener 还是有实现的，https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L47
https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L251

StateView.EMPTY 不需要了，就不用了。可以使用 emptyResource 代替：https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L37

**Comment by Awoodwhale** [comment]
> OnInflateListener 还是有实现的，https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L47 https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L251
> 
> StateView.EMPTY 不需要了，就不用了。可以使用 emptyResource 代替：https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L37

Thanks！
