### ISSUE TITLE
androidx.fragment.app.FragmentContainerView

### ISSUE THREAD

**Issue by luojt** [nukc/StateView#42]
如果parent为androidx.fragment.app.FragmentContainerView，会报错

**Comment by luojt** [comment]
使用navigation组件，单activity嵌套多个fragment，parent为androidx.fragment.app.FragmentContainerView

**Comment by nukc** [comment]
请了解 FragmentContainerView 的特性，你可以 inject activity 也可以 inject 具体的 fragment，也可以对具体的 view

**Comment by luojt** [comment]
`if(parent is androidx.fragment.app.FragmentContainerView){
                    return Injector.matchViewIfFragmentContainerView(parent, view)
                }`
`fun matchViewIfFragmentContainerView(parent: FragmentContainerView, view: View): StateView {
        val stateView = StateView(parent.context)
        setStateListAnimator(stateView, view)
        return stateView
    }`

**Comment by luojt** [comment]
FragmentContainerView 继承 FrameLayout，FrameLayout无法使用addview方法

**Comment by luojt** [comment]
`if(parent is FrameLayout){
                    return Injector.matchViewIfParentIsFrameLayout(parent, view)
                }`

**Comment by luojt** [comment]
```
fun matchViewIfParentIsFrameLayout(parent: FrameLayout, view: View): StateView {
        val stateView = StateView(parent.context)
        setStateListAnimator(stateView, view)
        return stateView
    }
```

**Comment by nukc** [comment]
不要去 inject FragmentContainerView ，https://developer.android.google.cn/reference/kotlin/androidx/fragment/app/FragmentContainerView
FragmentContainerView 虽然是继承了 FrameLayout，但并不是作为普通的 ViewGroup 那样。
你应该在 fragment 里使用 StateView

**Comment by luojt** [comment]
fragment 里面使用了stateview，布局文件是用了fragment标签，他的view.parent为FragmentContainerView

**Comment by luojt** [comment]
```
 <fragment
            android:id="@+id/host_fragment"
            android:name="*.navigation.NavHostFragmentHideShow"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:defaultNavHost="true"
            app:navGraph="@navigation/nav_main_graph" />
```

**Comment by nukc** [comment]
该 fragment 的 onCreateView 返回的 view 是什么，你是直接 inject 的这个 view 吗

**Comment by luojt** [comment]
是的，我新增了上述的判断，解决了该问题

**Comment by luojt** [comment]
```
override fun createStateView(){
        mStateView = StateView.inject(mViewBind.root)
    }
```

**Comment by luojt** [comment]
如果使用jetpack中的navigation组件，会有这样的场景

**Comment by nukc** [comment]
看样是需要加多个判断 FragmentContainerView，估计以后也会有新的这类特殊 ViewGroup

**Comment by nukc** [comment]
@luojt 已发版，v3.0.2

**Comment by luojt** [comment]
@nukc 收到，很优秀

**Comment by luojt** [comment]
@nukc 我觉得这样判断会不会更好一点
```
return if (viewGroup.parent is ViewGroup && viewGroup.parent !is FrameLayout) {
      wrap(viewGroup)
} else {
      Injector.wrapChild(viewGroup)
}
```
FragmentContainerView是FrameLayout的子类，我测试了一下可以

**Comment by nukc** [comment]
FragmentContainerView 才是特殊的，FrameLayout 是很常用的，且是正常的

**Comment by luojt** [comment]
好的，明白了

**Comment by csh159** [comment]
当不引用 androidx.fragment:fragment 的时候回报 java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/fragment/app/FragmentContainerView;
