### ISSUE TITLE
viewpager2+fragment的时候 切换会被隐藏！

### ISSUE THREAD

**Issue by csh159** [nukc/StateView#45]
通过  stateInject(binding.root)的方式

**Comment by nukc** [comment]
这个 binding.root 是哪个？

**Comment by nukc** [comment]
Demo: https://github.com/nukc/StateView/blob/kotlin/app/src/main/java/com/github/nukc/sample/ViewPager2Activity.kt
https://github.com/nukc/StateView/blob/kotlin/app/src/main/java/com/github/nukc/sample/InjectFragment.java

**Comment by csh159** [comment]
找到原因了 谢谢！
