### ISSUE TITLE
似乎有点问题呢

### ISSUE THREAD

**Issue by MrZhangX** [nukc/StateView#46]
我发现如果同时注册两个recycleView，只会显示一个recycleView，两个网络请求都是有数据的。
我在另外一个recycleView外面嵌套一层，使用嵌套的id就解决了。

我用的是java，但是发现setResource不生效。而且只显示一个重试。。

**Comment by nukc** [comment]
一个 StateView 实例只能 inject 一个 View，看实现原理就知道了；设置 empty error 等类型的 resource，还需要调用具体的 show 方法
