### ISSUE TITLE
父布局为SmartRefreshLayout显示异常问题

### ISSUE THREAD

**Issue by onlyeLC** [nukc/StateView#47]
父布局为SmartRefreshLayout时，通过StateView.inject(it)给其中子布局添加状态，无法正常显示

**Comment by onlyeLC** [comment]
父布局为SmartRefreshLayout时，通过StateView.inject(it)给其中子布局添加状态，无法正常显示

**Comment by nukc** [comment]
对于第三方组件，不兼容的话请直接在 xml 布局文件中使用
