### ISSUE TITLE
setOnRetryClickListener

### ISSUE THREAD

**Issue by hanshiyang** [nukc/StateView#48]
stateView  压根就没与这个函数 setOnRetryClickListener 不知道你是怎么写的

**Comment by nukc** [comment]
最新版源码：https://github.com/nukc/StateView/blob/kotlin/kotlin/src/main/java/com/github/nukc/stateview/StateView.kt#L47

Java Demo:
https://github.com/nukc/StateView/blob/kotlin/app/src/main/java/com/github/nukc/sample/CustomActivity.java#L28

Kotlin: 
```kotlin
       stateView.onRetryClickListener = object : StateView.OnRetryClickListener {
            override fun onRetryClick() {
                // do something
            }
        }
```
