### ISSUE TITLE
injectFragment throw IllegalStateException

### ISSUE THREAD

**Issue by TOPWARNING** [nukc/StateView#6]
if injected view is the rootview ,then parent.getParent() is null,so you can't add the view to another viewgroup(custom stateview) any more.
![image](https://cloud.githubusercontent.com/assets/6268829/23448091/eba33d68-fe89-11e6-9587-ba5797e1c3fd.png)
![image](https://cloud.githubusercontent.com/assets/6268829/23448126/14c62d5e-fe8a-11e6-8f6d-aa5670f40e50.png)

**Comment by nukc** [comment]
i will fix it

**Comment by nukc** [comment]
fixed in [v1.1.0](https://github.com/nukc/StateView/releases/tag/v1.1.0), and thanks your feedback.

**Comment by TOPWARNING** [comment]
well done!
