### ISSUE TITLE
How to set message in empty view

### ISSUE THREAD

**Issue by svkdvlp** [nukc/StateView#8]
I want to use one custom emptyview in entire app with different message and image.how to achive this?

**Comment by nukc** [comment]
Create a new layout  (layout's name must be base_empty/base_retry/base_loading), then run, it will be set the new layout. (gradle will replace with the new layout at build time)

**Comment by nukc** [comment]
```java
     View emptyView = mStateView.showEmpty();
     ((TextView) ((ViewGroup) emptyView).getChildAt(0)).setText("message");
```

if need a setMessage function, i will add in the next version.

**Comment by svkdvlp** [comment]
Thnks.close and please add in future.great lib.thanks

**Comment by nukc** [comment]
In v1.3.2, you can setOnInflateListener to set message, like [AnimatorActivity.java#L28](https://github.com/nukc/StateView/blob/master/app/src/main/java/com/github/nukc/sample/AnimatorActivity.java#L28)
