### ISSUE TITLE
在fragment的setUserVisibleHint中设置状态时,页面会空白,不显示任何设置的状态页面

### ISSUE THREAD

**Issue by a1048823898** [nukc/StateView#9]
如题

**Comment by nukc** [comment]
请提供更详细的信息或代码

**Comment by a1048823898** [comment]
public class TestFragment extends Fragment {

    private View mView;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        mView = inflater.inflate(R.layout.fragment_test, container, false);

        return mView;
    }

    @Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        if (isVisibleToUser && isAdded()) {
            StateView stateView = StateView.inject(mView, false);
            stateView.showRetry();
        }
    }
}

布局是一个LinearLayout,在setUserVisibleHint方法中设置状态,显示空白,但是在onCreateView中设置状态是正常的

**Comment by nukc** [comment]
setUserVisibleHint 方法走在 fragment 的生命周期的前面，同时请在 onCreateView 中进行 inject，如有需要，StateView 声明为全局，并在 setUserVisibleHint 中判断 StateView 是否为 null
